### ISSUE TITLE
Stratify TRN and linkage plots by year

### ISSUE THREAD

**Issue by bgcarlisle** [quest-bih/clinical-dashboard#13]
# Linkage plot

Start page: convert to line plot

One-UMC page: also line plot with "All" comparator

# TRN plot

Start page: stacked bar chart stratified by year

One-UMC page: ??

**Comment by bgcarlisle** [comment]
Done linkage plot https://github.com/quest-bih/clinical-dashboard/commit/5d5bc762e4be5deb75e42aad2a4f919d588343da

**Comment by bgcarlisle** [comment]
Will double-check with Daniel whether he really wants the TRN one stratified by year, because the other dimension is more informative and it would also be difficult to include all the data in a single graph

**Comment by bgcarlisle** [comment]
Gah I'm not finding the email about this, but tempted to close this issue unless it's brought up again

**Comment by delwen** [comment]
It'd be interesting to see the trend over time (as for all other metrics). 

For the Start page, this could be a line plot (2 lines, abstract and full text) or a stacked bar graph (as OA).
More challenging for the One UMC page: we'd probably need a line plot showing all vs. abstract, with a toggle that switches to showing full text.

Do you see drawbacks? Or advantages of the current version?

**Comment by bgcarlisle** [comment]
The advantage to the current version is that it focuses on the difference between full-text and abstract, and the one-UMC page might get a bit unwieldy

I think we will lose that focus if we change it, and we won't get much out of seeing it on a per-year basis

That said, I could be convinced

**Comment by delwen** [comment]
Yeah I'm also on the fence on this one. I think we can still show the trend over time without losing the abstract vs full-text difference, but I agree that the focus will be different.

Suggest we table this for now, but we can re-visit if we get further feedback on this point. Closing the issue for now.
