### ISSUE TITLE
Some of the methods tool tips are not fully visible

### ISSUE THREAD

**Issue by delwen** [quest-bih/clinical-dashboard#3]
Some of the methods tool tips are not fully visible. Seems to apply to the following metrics on the "Start" and "One UMC" pages:
- Prospective registration
- EUCTR reporting
- Open Access

Seems to be the same on Safari, Firefox, and Chrome.

**Comment by bgcarlisle** [comment]
https://user-images.githubusercontent.com/3100614/128983703-834cd4ef-db5c-4d0b-bac8-52864c4b2f43.mp4

**Comment by bgcarlisle** [comment]
Fixed it!

https://github.com/quest-bih/clinical-dashboard/commit/0b6e06a5bd6643f6951021cff506b391f909b73c

**Comment by delwen** [comment]
> Fixed it!
> 
> [0b6e06a](https://github.com/quest-bih/clinical-dashboard/commit/0b6e06a5bd6643f6951021cff506b391f909b73c)

Awesome! 👍
