### ISSUE TITLE
Remove duplicate publications for OA plots

### ISSUE THREAD

**Issue by delwen** [quest-bih/clinical-dashboard#30]
Some of the trials in the IV sample are associated with the same publication. For Open Access plots, we should first deduplicate these (based on DOI).

**Comment by maia-sh** [comment]
I think this is easiest if @bgcarlisle does a `distinct(doi)` before making the plot. keep in mind then to change the language to the unit of analysis of publication and not trial. i decided to keep duplicates in trn paper to keep the unit of analysis to trials throughout. aka, x trials have oa pubs vs. x pubs are oa.

**Comment by bgcarlisle** [comment]
This will fix the OA plots! https://github.com/quest-bih/clinical-dashboard/commit/eb06b63a84eabad400e01a61ffc5df9056a7a8a4
