### ISSUE TITLE
Make absolute number plot toggle more prominent

### ISSUE THREAD

**Issue by delwen** [quest-bih/clinical-dashboard#39]
Seems like the toggle to view absolute numbers is sometimes being overlooked. Shall we make it more prominent? We could increase the font, change the colour (maybe the pink colour used for the descriptor texts?) , or change the location (or other). Just adding to our TODO - other ideas?

**Comment by delwen** [comment]
@bgcarlisle: I think a pragmatic first step would be to increase font size and apply the same purple colour as descriptor text.

**Comment by bgcarlisle** [comment]
Do you mean the checkbox in the Open Access section?

**Comment by delwen** [comment]
Yeah, the "show absolute numbers" checkbox. It seems it's not always being picked up, but it's pretty key for interpretations especially for the green OA plot. Open to other ideas on how to make this more visible!
