### ISSUE TITLE
Migrate application of exclusion criteria for clinical dashboard to this repository

### ISSUE THREAD

**Issue by delwen** [quest-bih/clinical-dashboard#4]
As discussed, it would make sense to migrate the application of exclusion criteria to this repo. Suggest to:
- Include line to download data directly from the from the [intovalue-data repository](https://raw.githubusercontent.com/maia-sh/intovalue-data/main/data/processed/intovalue.csv)
- Apply [exclusion criteria](https://github.com/maia-sh/intovalue-data/blob/main/R/05_prepare-clinical-dashboard-data.R) directly here
  - Include code to create the nested and unnested datasets
  - Include code to apply intovalue-city-transforms 
- Include more description of the folder structure (in particular data and prep folders)?

Other thoughts?

**Comment by bgcarlisle** [comment]
There's now an R script that does everything that "R script 5" used to do:

https://github.com/quest-bih/clinical-dashboard/commit/3422a676fd66590e61d528a186324a3c8d9a9f8c#diff-b10b18f906fcd1ca87847667a5011cd5974171625d4173caf48507d49d5d68ee

You have to download the .rds from the other repo (instructions in comments), but then the script applies the exclusions, creates the nested and unnested versions, applies the city name transformations and writes them to the `data/` folder

**Comment by bgcarlisle** [comment]
I also added a bit of description to the `README.md`
