### ISSUE TITLE
Duplication of Munich city for updated dataset for prospective reg in CT.gov

### ISSUE THREAD

**Issue by delwen** [quest-bih/clinical-dashboard#42]
The splitting of city names generates an extra variable for Munich. We now have 3 variables for Munich instead of 2: `München`,`LMU`, and `TU`. We should only have `LMU München` and `TU München`. Need to adapt the string split.

**Comment by bgcarlisle** [comment]
This fixes the issue by inserting a dash between LMU and München in the underlying data sets

https://github.com/quest-bih/clinical-dashboard/commit/fae523216af7c2967f3e7f9dc5796ed0ed473d6f

All we need to do is update the CSV's on the server

**Comment by delwen** [comment]
Thanks. We still have a couple of differences in the way UMCs are encoded in the updated CT.gov prospective registration dataset vs. in the transformed IntoValue dataset (`city` in https://github.com/quest-bih/clinical-dashboard/blob/dashboard-updates/prep/intovalue-city-transforms.csv):
- "Duisburg-Essen" (transformed IntoValue) vs. "Duisburg" (prospective reg CT.gov) 
- "Halle-Wittenberg" (transformed IntoValue) vs. "Halle" (prospective reg CT.gov)
- "Witten/Herdecke" (transformed IntoValue) vs "Witten-Herdecke" (prospective reg CT.gov)

This is problematic for the One UMC page since we select a UMC based on names in the transformed IntoValue dataset. As a result, the CT.gov data for those UMCs won't display even though we have the data.
**Proposed solutions:** a) we could replace the UMC names in the prospective reg CT.gov dataset to match that in the transformed IntoValue dataset (which is the preferred name), b) we could create a separate look-up table for the prospective reg CT.gov dataset, as we did for IntoValue. Let's discuss.

Another issue is that in the IntoValue dataset, we have "Schleswig-Holstein" whereas in the prospective reg CT.gov dataset this UMC is represented as 2 separate UMCs ("Kiel" and "Lübeck").
**Proposed solution:** We could combine the data for Kiel and Lübeck in the prospective reg in CT.gov dataset (under Schleswig-Holstein). Let's discuss.

**Comment by delwen** [comment]
Just a note that regardless of what we decide wrt harmonization of city names between IntoValue and the updated CT.gov prospective registration dataset, we should also remember to adjust EUTT names accordingly.

**Comment by delwen** [comment]
@maia-sh, @bgcarlisle: let's keep track of our decisions on harmonisation of city names here

**Comment by delwen** [comment]
Resolved with https://github.com/maia-sh/intovalue-data/pull/19 and https://github.com/maia-sh/intovalue-data/pull/22
