### ISSUE TITLE
Add Impressum and Datenschutz to the dashboard

### ISSUE THREAD

**Issue by delwen** [quest-bih/clinical-dashboard#43]
Let's discuss what to include.

**Comment by bgcarlisle** [comment]
Oh no I lost the email where you sent me the details from the Charité dashboard D:

**Comment by delwen** [comment]
Looks great! In the Charité dashboard, the Impressum/Datenschutz are on each page - not sure if that's also needed here? Also, we should update the contact person for the Impressum (I'd suggest Daniel).

**Comment by bgcarlisle** [comment]
Done! https://github.com/quest-bih/clinical-dashboard/commit/f0e194352e229f48bf9084f02b5191746cc0b7cc
