### ISSUE TITLE
"Not applicable" does not update with registry toggle

### ISSUE THREAD

**Issue by delwen** [quest-bih/clinical-dashboard#47]
In the prospective registration plot in the One UMC page, the "Not applicable" does not update after changing the registry. For example, if you select Halle-Wittenberg, you get N/A for ClinicalTrials.gov (as expected as no CT.gov trials). But if you switch to DRKS, it still says N/A despite there being DRKS trials for that UMC.

**Comment by bgcarlisle** [comment]
This one was, surprisingly, working correctly

For the One UMC plot, we had chosen to display only the numbers from 2017

I have changed this to show the numbers from the latest year with any trials in it

Done! https://github.com/quest-bih/clinical-dashboard/commit/01f84bf7e64696ad58f9f8c4e3448176c370de1a

**Comment by delwen** [comment]
Agree that's a better solution. But in this particular case, does Halle-Wittenberg show any data in the One UMC page for prospective reg in CT.gov? My assumption is that it doesn't because the city name "Halle-Wittenberg" is not in the updated CT.gov prospective reg dataset (in that dataset it has the city name "Halle").
