### ISSUE TITLE
Change in the mouse overs

### ISSUE THREAD

**Issue by delwen** [quest-bih/clinical-dashboard#54]
The absolute numbers (mouse-overs) are sometimes also in the plot itself (e.g., OA plots on the Start page) and sometimes not (e.g., reporting of TRN in abstract and full text). Maybe related to newer version of Shiny? I personally find this a bit cluttered and lean towards just having mouse overs, if possible.

**Comment by delwen** [comment]
@ontogenerator just realised I already had an issue open for this 😄

- [ ] TODO: We agreed that we'll remove the display of the nums/denoms on the OA plots as it is quite cluttered. The num/denoms will still be displayed in the mouse over.

**Comment by ontogenerator** [comment]
@delwen  check out the current version and see if you like it.
