### ISSUE TITLE
Missing prep/transform-intovalue.R

### ISSUE THREAD

**Issue by maia-sh** [quest-bih/clinical-dashboard#56]
Hi @bgcarlisle and @delwen,

Just trying to recall why `prep/transform-intovalue.R` is not pushed to remote and whether we can change that (or separate out scripts into what we can push and what we don't):
https://github.com/quest-bih/clinical-dashboard/blob/main/app.R#L27

**Comment by delwen** [comment]
@maia-sh: we have both the `prep/transform-intovalue.R` and `prep/eutt-history.R` locally. The plan is to have these remotely again

**Comment by delwen** [comment]
Re-added the relevant scripts!
