### ISSUE TITLE
Decide on other instance of hardcoded eutt_date

### ISSUE THREAD

**Issue by delwen** [quest-bih/clinical-dashboard#57]
https://github.com/quest-bih/clinical-dashboard/blob/c690b317495db987fb45bf1f142c9ed80fc130e1/start_page_plots.R#L267

:wave: @ontogenerator we should keep in mind this hardcoded instance as well, depending on how far back we want to go in this plot. The previous download date is still in there, which takes you back to the earliest EUTT we can extract (December 2020). The alternative is to set that to `eutt_date` (which we did so far). But now I'm thinking why not go back to earliest data we can get.

Either way, we should probably decide and change this to avoid any surprises down the line.

**Comment by ontogenerator** [comment]
Yes, I think we should just go back to the earliest data we have, rather than having this arbitrary time window of 1.5 years.
Happy to change this, if we're in agreement.

**Comment by ontogenerator** [comment]
Removed filter, which takes us back to December 2020 for the EUTT.
