### ISSUE TITLE
Update sponsor info in trial characteristics table

### ISSUE THREAD

**Issue by delwen** [quest-bih/clinical-dashboard#64]
The number of industry sponsors for ClinicalTrials.gov trials in the trials characteristics table is incorrect. See a detailed description here: https://github.com/quest-bih/ctt-discussions/discussions/50.

TODO:
- [x]  Make search for industry sponsor case insensitive in https://github.com/quest-bih/clinical-dashboard/blob/527ab830a8f81b938348ddf0825f340c59760306/trial_characteristics_page.R#L20 and https://github.com/quest-bih/clinical-dashboard/blob/527ab830a8f81b938348ddf0825f340c59760306/trial_characteristics_page.R#L106
- [x] Update live dashboard with new trial characteristics table

**Comment by ontogenerator** [comment]
Hi @delwen, I pushed to main already by mistake. Is that OK or should I make a pull request instead? It was a very minor change. Btw, the source file data/ct-dashboard-intovalue-all.csv previously had the sponsor categories unified without case differences (only "Industry" and no "INDUSTRY" in main_sponsor). I retrieved it again withprep-intovalue and it now has all the different cases/spellings. Still, the total number of industry_sponsor == TRUE was 444. If all is good then I will pull to the live dashboard.

**Comment by delwen** [comment]
Hi @ontogenerator, thanks for looking into this! Let's keep it in main for now, but going forwards let's stick with pull requests even for small changes. I'm confused about what you said about the existing data/ct-dashboard-intovalue-all.csv. The sponsor categories shouldn't have been unified (at least I couldn't find any code to that effect), although that would be consistent with the code that was in the `trial_characteristics_page.R`, i.e., before you made the change. I also reran `prep-intovalue.R` on the `trials.csv` file from our dashboard release (https://github.com/maia-sh/intovalue-data/releases/tag/v1.1) and the sponsor categories were also not unified. Any idea what might have happened here, or why we're seeing something different?

Also @maia-sh should we be cautious with language around industry sponsor? For example for DRKS, could it be that what we categorise as Industry is actually something else? (see https://github.com/maia-sh/intovalue-data/blob/817c24afa007dbc222cd28fe9b6090c4355ec96e/scripts/08_process-drks.R#L225)

**Comment by maia-sh** [comment]
DRKS sponsor definition was taken from IntoValue. See [DRKS FAQs](https://www.bfarm.de/EN/BfArM/_FAQ/DRKS/faq-liste.html?nn=916850)
> **Is my clinical trial an IST/IIT?**:
> IST/IIT stands for investigator sponsored trial/investigator initiated trial. The responsibility for initiation and organisation of such a study (the sponsorship) rests with the respective individual or the institution to which this person belongs (e.g. university, hospital, public institute, non-profit organisation, patient organisation). The objective is a gain in scientific knowledge.
> In contrast, commercial trials intend to generate future profits or cost savings. The sponsorship normally rests with a private business (e.g. a pharmaceutical company) but can also apply to a study financed in whole or partly from public funds.
> In conclusion, a study, which is e.g. organized and financed by a public health insurance, can only be accounted to an IST/IIT, if there is no commercial interest.

Also see [DRKS Statistics](https://www.bfarm.de/DE/Das-BfArM/Aufgaben/Deutsches-Register-Klinischer-Studien/Statistik/_node.html;jsessionid=7AE4C666DE8C138FC1FBC82C2D05A7A1.intranet231)
> **Wissenschaftsinitiierte Studien (Investigator Initiated Trials – IIT) im DRKS**
> Der Anteil registrierter wissenschaftsinitiierter Studien pro Jahr liegt seit 2010 unverändert hoch bei ca. 90 %. Diese Studien werden in der Regel von Universitäten durchgeführt.
> Kommerzielle klinischen Arzneimittelprüfungen müssen zwingend im EU-CTR (EU Clinical Trials Register) registriert werden bzw. spätestens seit 31.01.2023 im CTIS (Clinical Trials Information System) der EU. Eine zusätzliche Registrierung dieser Studien in einem weiteren WHO-Primärregister ist nicht erforderlich bzw. von der WHO explizit nicht gewünscht, wenn keine besonderen Gründe vorliegen.
> ![drks-iit-plot](https://www.bfarm.de/SharedDocs/Bilder/DE/Diagramme/DRKS/iit.png?__blob=normal)

**Comment by delwen** [comment]
hey @ontogenerator, we should be good to go. You can update the live version of the dashboard.

**Comment by ontogenerator** [comment]
Updated now.
