### ISSUE TITLE
Review of Methods page content

### ISSUE THREAD

**Issue by delwen** [quest-bih/clinical-dashboard#7]
I made some updates to the Methods page. Could you review the content of each metric (until line 345)? Each section reports on what is measured, how it was measured, and the limitations to consider.

No need to look at the tooltips as this will just be a condensed version of what's in the methods.

Thanks!

https://github.com/quest-bih/clinical-dashboard/blob/736346c59c73f03102e4d4e82e04d8635cc619bf/methods_page.R#L1

**Comment by bgcarlisle** [comment]
I'm on it!!

**Comment by bgcarlisle** [comment]
Okay I reviewed the Methods page and made some small edits: https://github.com/quest-bih/clinical-dashboard/commit/91d4768e68a38a53b12efa50848129f9e2be429d

If these meet with your approval, go ahead and make a PR!

**Comment by delwen** [comment]
Thanks for your suggestions, @bgcarlisle! Looks good to me. Will just wait for @maia-sh's comments and then make a PR!

**Comment by bgcarlisle** [comment]
You'll need to rebase on the `main` branch because I just pushed a fix for the bug with the one-UMC plots
