### ISSUE TITLE
Placement of legend on the one UMC plots

### ISSUE THREAD

**Issue by delwen** [quest-bih/clinical-dashboard#8]
General: suggest to increase the y-axis limit so that 100% values are still fully visible.

One UMC page: the legend sometimes obscure the data points (see below). Would another placement be possible?
<img width="263" alt="Screenshot 2021-08-13 at 13 44 06" src="https://user-images.githubusercontent.com/18604247/129352711-8db89f08-ce14-438a-ac4c-2398ff7d865f.png">

**Comment by bgcarlisle** [comment]
Were you thinking top-left?

**Comment by delwen** [comment]
I guess that would be the placement less likely to overlap. Maybe also with a transparent background?

**Comment by bgcarlisle** [comment]
Not sure if plot_ly supports transparent backgrounds, but I'll give it a shot!

**Comment by bgcarlisle** [comment]
Done! https://github.com/quest-bih/clinical-dashboard/commit/362469274c1af3ecd2a44013e35c321b9fa42306
