### ISSUE TITLE
Display OA data over time

### ISSUE THREAD

**Issue by delwen** [quest-bih/clinical-dashboard#9]
Display the OA data over time in the Start and One UMC pages.

- We don't have a publication for each year, and we also have quite different publication numbers across some years
  - We could address this by setting a threshold or by binning
- Settle how to display the data in the One UMC page. Issue is that this page compares data for one UMC and the average UMC data. So adding yearly progression would lead to a lot of stacked bar charts which would be tricky to interpret. Possible solutions:
  - We could switch to line plots but then we'd probably have to do without the OA categories (not ideal)
  - We bin the data which should give us a more manageable number of bar charts (we could keep the current view)
  - As suggested by @bgcarlisle, we could add a toggle to switch between a) stacked bar chart (with OA categories but not yearly progression); b) line plot (without OA categories but with yearly progression).

To be discussed!

**Comment by bgcarlisle** [comment]
Done! https://github.com/quest-bih/clinical-dashboard/commit/585a7240a265067c645b6c80aebf67933124b1c2
